-- ====================================================================
-- Smart Parking Monitoring & RFID Member System Database Schema
-- Reference: TRD Section 13 & DRD Section 12
-- Target: Supabase (PostgreSQL)
-- ====================================================================

-- 13.1 parking_members
create table if not exists parking_members (
    id bigint generated by default as identity primary key,
    rfid_uid text unique not null,
    member_name text not null,
    license_plate text not null,
    vehicle_type text default 'car',
    status text default 'active',
    inside_parking boolean default false,
    created_at timestamptz default now()
);

alter table parking_members add column if not exists inside_parking boolean default false;

-- 13.2 rfid_scans
create table if not exists rfid_scans (
    id bigint generated by default as identity primary key,
    uid text not null,
    device_id text,
    created_at timestamptz default now()
);

-- 13.3 parking_slots
create table if not exists parking_slots (
    id bigint generated by default as identity primary key,
    slot_code text unique not null,
    status text default 'available',
    sensor_value integer,
    device_id text,
    updated_at timestamptz default now()
);

-- 13.4 iot_devices
create table if not exists iot_devices (
    id bigint generated by default as identity primary key,
    device_id text unique not null,
    device_name text,
    owner_name text,
    api_key text unique,
    device_type text default 'multi-sensor',
    status text default 'offline',
    last_seen timestamptz,
    created_at timestamptz default now()
);

-- Migrations for existing deployments
alter table iot_devices add column if not exists owner_name text;
alter table iot_devices add column if not exists api_key text unique;
alter table iot_devices add column if not exists device_type text default 'multi-sensor';
alter table iot_devices add column if not exists created_at timestamptz default now();


-- 13.5 sensor_data
create table if not exists sensor_data (
    id bigint generated by default as identity primary key,
    device_id text,
    sensor_type text,
    sensor_value double precision,
    created_at timestamptz default now()
);

-- 13.6 app_users (Authentication & Multi-Role)
create table if not exists app_users (
    id bigint generated by default as identity primary key,
    username text unique not null,
    password_hash text not null,
    role text not null default 'student', -- 'admin' or 'student'
    full_name text not null,
    device_id text, -- linked device for student
    created_at timestamptz default now()
);

-- 13.7 audit_forensic_logs (Forensic Audit & Anti-Passback / Tailgating)
create table if not exists audit_forensic_logs (
    id bigint generated by default as identity primary key,
    event_type text not null, -- 'entry_granted', 'exit_granted', 'anti_passback_violation', 'tailgating_detected', 'unauthorized_scan'
    rfid_uid text,
    member_name text,
    license_plate text,
    device_id text,
    photo_url text, -- Captured vehicle snapshot (SVG data-uri or image path)
    tailgating_detected boolean default false,
    details text,
    created_at timestamptz default now()
);

-- ====================================================================
-- Row Level Security (RLS) Configuration
-- Nonaktifkan RLS agar ESP32-S3 dan Web Streamlit anon-key dapat membaca & menulis data
-- ====================================================================
alter table parking_members disable row level security;
alter table rfid_scans disable row level security;
alter table parking_slots disable row level security;
alter table iot_devices disable row level security;
alter table sensor_data disable row level security;
alter table app_users disable row level security;
alter table audit_forensic_logs disable row level security;

-- ====================================================================
-- Seed / Initial Realistic Data
-- ====================================================================

-- Seed IoT Devices (ESP32 Smart Parking System)
insert into iot_devices (device_id, device_name, status, last_seen)
values 
    ('GATE-01', 'ESP32 Smart Parking Controller (Gate & 3 Slots)', 'online', now()),
    ('PARKING-01', 'ESP32 Parking Extension Node', 'online', now())
on conflict (device_id) do update 
set 
    device_name = excluded.device_name,
    status = excluded.status,
    last_seen = excluded.last_seen;

-- Seed Parking Slots (P01 to P03 matching ESP32: Slot 1, Slot 2, Slot 3)
-- Nilai Sensor IR Digital: 0 = Terisi (Active LOW), 1 = Kosong (HIGH)
insert into parking_slots (slot_code, status, sensor_value, device_id, updated_at)
values 
    ('P01', 'available', 1, 'GATE-01', now()),
    ('P02', 'occupied', 0, 'GATE-01', now()),
    ('P03', 'available', 1, 'GATE-01', now())
on conflict (slot_code) do update 
set 
    status = excluded.status,
    sensor_value = excluded.sensor_value,
    device_id = excluded.device_id,
    updated_at = excluded.updated_at;

-- Seed Parking Members
insert into parking_members (rfid_uid, member_name, license_plate, vehicle_type, status, created_at)
values 
    ('A3F21C12', 'Rahmat Hidayat', 'BG 1234 RH', 'car', 'active', now() - interval '2 days'),
    ('B4E22D33', 'Budi Santoso', 'B 5678 CD', 'car', 'active', now() - interval '1 day'),
    ('C5F33E44', 'Siti Aminah', 'D 9012 EF', 'motorcycle', 'inactive', now() - interval '12 hours')
on conflict (rfid_uid) do update 
set 
    member_name = excluded.member_name,
    license_plate = excluded.license_plate,
    vehicle_type = excluded.vehicle_type,
    status = excluded.status;

-- Seed Sample RFID Scans
insert into rfid_scans (uid, device_id, created_at)
values 
    ('A3F21C12', 'GATE-01', now() - interval '10 minutes'),
    ('B4E22D33', 'GATE-01', now() - interval '5 minutes'),
    ('D6A44B55', 'GATE-01', now() - interval '1 minute');

-- Seed Sample Sensor Data
insert into sensor_data (device_id, sensor_type, sensor_value, created_at)
values 
    ('GATE-01', 'ultrasonic', 18.5, now() - interval '30 seconds'),
    ('PARKING-01', 'ir', 450.0, now() - interval '25 seconds'),
    ('PARKING-01', 'ir', 2150.0, now() - interval '20 seconds'),
    ('PARKING-01', 'ir', 420.0, now() - interval '15 seconds'),
    ('PARKING-01', 'ir', 510.0, now() - interval '10 seconds');

-- Seed App Users (Admin & Siswa)
-- Password 'admin123' -> 240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9
-- Password 'siswa123' -> ca82d8a67832679fdc39c9156f087e31236b833ee7371eb3d6e081aeb90016c9
insert into app_users (username, password_hash, role, full_name, device_id)
values 
    ('admin', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'admin', 'Administrator Smart Parking', null),
    ('siswa1', 'ca82d8a67832679fdc39c9156f087e31236b833ee7371eb3d6e081aeb90016c9', 'student', 'Ahmad Zaki', 'DEV-SISWA-01')
on conflict (username) do update 
set 
    password_hash = excluded.password_hash,
    role = excluded.role,
    full_name = excluded.full_name,
    device_id = excluded.device_id;

